name: generate animation SNK

on:
  schedule:
    - cron: "0 */24 * * *" # every 6 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.0.0
            
